import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:linguaflow/models/lesson_model.dart';
import 'package:linguaflow/models/transcript_line.dart';

class LocalLessonService {
  
  Future<List<LessonModel>> fetchLessons(String languageCode) async {
    try {
      // Load the file generated by your Python script
      final String jsonString = await rootBundle.loadString('assets/data/lessons_$languageCode.json');
      final List<dynamic> data = json.decode(jsonString);
      
      return data.map((jsonItem) {
        // Handle ID mapping properly (some IDs might be "yt_XYZ", some might be pure "XYZ")
        final id = jsonItem['id']?.toString() ?? 'unknown_${DateTime.now().millisecondsSinceEpoch}';
        
        return LessonModel(
          id: id,
          userId: jsonItem['userId'] ?? 'system',
          title: jsonItem['title'] ?? 'Untitled',
          language: jsonItem['language'] ?? languageCode,
          content: jsonItem['content'] ?? '',
          // Map sentences list
          sentences: (jsonItem['sentences'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ?? [],
          // Map transcript list (IMPORTANT for video seeking)
          transcript: (jsonItem['transcript'] as List<dynamic>?)
              ?.map((e) => TranscriptLine.fromMap(e))
              .toList() ?? [],
          createdAt: DateTime.tryParse(jsonItem['createdAt'] ?? '') ?? DateTime.now(),
          imageUrl: jsonItem['imageUrl'],
          type: jsonItem['type'] ?? 'text',
          difficulty: jsonItem['difficulty'] ?? 'intermediate',
          videoUrl: jsonItem['videoUrl'],
          isFavorite: jsonItem['isFavorite'] ?? false,
          progress: jsonItem['progress'] ?? 0,
        );
      }).toList();

    } catch (e) {
      print("❌ Error loading local lessons for $languageCode: $e");
      return [];
    }
  }
}