import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:linguaflow/models/lesson_model.dart';
import 'package:linguaflow/models/transcript_line.dart';

class YoutubeImportService {
  // ✅ Correct FastAPI Endpoint
  final String _backendUrl = "https://reikom123-linguaflow-api.hf.space/api/v1/extract";

  Future<LessonModel?> importVideo(
    String videoUrl,
    String targetLangCode,
    String userId,
  ) async {
    try {
      print("🚀 Sending request to FastAPI Backend...");

      final response = await http.post(
        Uri.parse(_backendUrl),
        headers: {"Content-Type": "application/json"},
        // ✅ FIXED: Send specific keys matching your Python VideoRequest model
        body: jsonEncode({
          "url": videoUrl,
          "lang": targetLangCode,
        }),
      );

      if (response.statusCode == 200) {
        // Decode response (handling UTF-8 for subtitles)
        final resultData = jsonDecode(utf8.decode(response.bodyBytes));

        // ✅ FIXED: No more ['data'][0]. The response IS the data.
        
        // Check for error sent from python logic
        if (resultData.containsKey('error')) {
          throw Exception("Backend Error: ${resultData['error']}");
        }

        // 1. Parse Transcripts
        List<dynamic> rawTranscript = resultData['transcript'];
        List<TranscriptLine> transcriptLines = rawTranscript.map((item) {
          return TranscriptLine(
            text: item['text'],
            start: (item['start'] as num).toDouble(),
            end: (item['end'] as num).toDouble(),
          );
        }).toList();

        // 2. Parse Full Content
        String fullContent = resultData['fullContent'];
        List<String> sentences = fullContent
            .split(RegExp(r'(?<=[.!?])\s+'))
            .where((s) => s.trim().isNotEmpty)
            .toList();

        return LessonModel(
          id: '', // Generated by Firestore usually
          userId: userId,
          title: resultData['title'],
          language: targetLangCode,
          content: fullContent,
          sentences: sentences,
          transcript: transcriptLines,
          createdAt: DateTime.now(),
          imageUrl: resultData['imageUrl'],
          type: 'video',
          difficulty: 'intermediate',
          videoUrl: videoUrl,
          isFavorite: false,
          progress: 0,
        );
      } else {
        print("❌ Server Error: ${response.body}");
        throw Exception("Server failed: ${response.statusCode}");
      }
    } catch (e) {
      print("CRITICAL IMPORT ERROR: $e");
      rethrow;
    }
  }
}