import 'dart:async';
import 'package:logging/logging.dart';
import 'package:linguaflow/models/lesson_model.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

class YouTubeService {
  final YoutubeExplode _yt = YoutubeExplode();
  final Logger log = Logger("YouTubeService");

  YouTubeService() {
    // Enable verbose logging for debugging
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((record) {
      // Print logs (optional: write to file)
      print('[${record.level.name}] ${record.time}: ${record.message}');
    });
  }

  /// Core search query by language
  String _getSearchQuery(String languageCode) {
    switch (languageCode) {
      case 'es': return 'Spanish comprehensible input';
      case 'fr': return 'French comprehensible input';
      case 'de': return 'German comprehensible input';
      case 'it': return 'Italian comprehensible input';
      case 'pt': return 'Portuguese comprehensible input';
      case 'ja': return 'Japanese comprehensible input';
      default: return 'English learning stories';
    }
  }

  /// Public method: returns max 5 lessons
  Future<List<LessonModel>> fetchRecommendedVideos(String languageCode) async {
    log.info("Searching for videos in language: $languageCode");

    try {
      final query = _getSearchQuery(languageCode);

      final searchResults = await _yt.search.search(query);

      if (searchResults.isEmpty) {
        log.warning("No search results.");
        return _getFallbackLessons(languageCode);
      }

      List<LessonModel> valid = [];
      int processed = 0;

      // Process max 8 videos and stop once 5 valid are found
      for (final video in searchResults) {
        if (valid.length >= 5 || processed >= 8) break;
        processed++;

        await Future.delayed(const Duration(milliseconds: 250)); // avoid rate-limit

        try {
          final lesson = await _processVideo(video, languageCode);
          if (lesson != null) valid.add(lesson);
        } catch (e) {
          log.severe("Video failed '${video.title}': $e");
        }
      }

      if (valid.isEmpty) {
        log.warning("All scrapes failed. Returning fallback lessons.");
        return _getFallbackLessons(languageCode);
      }

      log.info("Completed. Found ${valid.length} lessons.");
      return valid;
    } catch (e) {
      log.severe("CRITICAL ERROR fetching YouTube videos: $e");
      return _getFallbackLessons(languageCode);
    }
  }

  /// PROCESS SINGLE VIDEO
  Future<LessonModel?> _processVideo(Video video, String languageCode) async {
    log.info("Processing: ${video.title}");

    ClosedCaptionManifest manifest;

    try {
      manifest = await _yt.videos.closedCaptions.getManifest(video.id);
    } catch (e) {
      log.warning("No caption manifest for '${video.title}': $e");
      return null;
    }

    if (manifest.tracks.isEmpty) {
      log.warning("No captions at all for '${video.title}'. Skipping");
      return null;
    }

    // ---------- LANGUAGE SEARCH ----------
    var tracks = manifest.getByLanguage(languageCode);

    if (tracks.isEmpty) {
      // Try fuzzy match (e.g. fr-FR, fr-CA)
      tracks = manifest.tracks.where((t) {
        final code = t.language.code.toLowerCase();
        return code == languageCode ||
            code.startsWith(languageCode.toLowerCase());
      }).toList();
    }

    if (tracks.isEmpty) {
      log.warning("No matching caption track in '$languageCode' for '${video.title}'.");
      return null;
    }

    // Prefer human-created subtitles
    final selected = tracks.firstWhere(
      (t) => !t.isAutoGenerated,
      orElse: () => tracks.first,
    );

    ClosedCaptionTrack captionTrack;

    try {
      captionTrack = await _yt.videos.closedCaptions.get(selected);
    } catch (e) {
      log.severe("Caption download failed (XML crash) for '${video.title}': $e");
      return null;
    }

    // ---------- BUILD CONTENT ----------
    final sb = StringBuffer();
    for (var c in captionTrack.captions) {
      sb.write(c.text);
      sb.write(" ");
    }

    final content = sb.toString().trim();

    if (content.length < 50) {
      log.warning("Caption content too short for '${video.title}'. Skipping.");
      return null;
    }

    log.info("Scraped successfully: ${video.title}");

    return LessonModel(
      id: "yt_${video.id}",
      userId: "system",
      title: video.title,
      language: languageCode,
      content: content,
      sentences: _splitIntoSentences(content),
      createdAt: DateTime.now(),
      imageUrl: video.thumbnails.highResUrl,
      type: "video",
      difficulty: _analyzeDifficulty(content),
      videoUrl: video.url,
      isFavorite: false,
    );
  }

  // ------------ UTILITIES ------------

  List<String> _splitIntoSentences(String text) {
    return text
        .split(RegExp(r'[.!?]+'))
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList();
  }

  String _analyzeDifficulty(String text) {
    final words = text.split(' ');
    if (words.isEmpty) return 'intermediate';
    final avg = words.join().length / words.length;
    if (avg < 4.5) return 'beginner';
    if (avg > 6.0) return 'advanced';
    return 'intermediate';
  }

  // --- FALLBACK DEMO DATA ---
  List<LessonModel> _getFallbackLessons(String lang) {
    return [
      LessonModel(
        id: 'yt_fallback_1',
        userId: 'system',
        title: '${lang.toUpperCase()} for Beginners (Demo)',
        language: lang,
        content:
            "This is a demo lesson. YouTube scraping was blocked or failed.",
        sentences: ["This is a demo lesson."],
        createdAt: DateTime.now(),
        imageUrl: 'https://img.youtube.com/vi/p_IhotL7hLI/hqdefault.jpg',
        type: 'video',
        difficulty: 'beginner',
        videoUrl: 'https://youtube.com/watch?v=ybfyLfI5Ml0',
        isFavorite: false,
      ),
    ];
  }

  void dispose() {
    _yt.close();
  }
}
