// import 'dart:async';
// import 'package:linguaflow/models/lesson_model.dart';
// import 'package:youtube_explode_dart/youtube_explode_dart.dart';

// class YouTubeService {
//   final _yt = YoutubeExplode();

//   String _getSearchQuery(String languageCode) {
//     switch (languageCode) {
//       case 'es': return 'Spanish comprehensible input subtitles';
//       case 'fr': return 'French comprehensible input subtitles';
//       case 'de': return 'German comprehensible input subtitles';
//       case 'it': return 'Italian comprehensible input subtitles';
//       case 'pt': return 'Portuguese comprehensible input subtitles';
//       case 'ja': return 'Japanese comprehensible input subtitles';
//       default: return 'English learning stories';
//     }
//   }

//   Future<List<LessonModel>> fetchRecommendedVideos(String languageCode) async {
//     print("🎥 YOUTUBE: Searching for '$languageCode'...");
    
//     try {
//       final query = _getSearchQuery(languageCode);
      
//       // 1. Search for videos
//       final searchResults = await _yt.search.search(query);
      
//       if (searchResults.isEmpty) {
//         print("   ⚠️ No search results. Loading Backup.");
//         return _getFallbackLessons(languageCode);
//       }

//       List<LessonModel> validLessons = [];
//       int attempts = 0;
      
//       // 2. Process results one by one
//       for (var video in searchResults) {
//         if (validLessons.length >= 5 || attempts >= 8) break;
//         attempts++;

//         // Small delay to be polite
//         await Future.delayed(Duration(milliseconds: 200));

//         try {
//           final lesson = await _processVideo(video, languageCode);
//           if (lesson != null) {
//             validLessons.add(lesson);
//           }
//         } catch (e) {
//           // If scraping fails for this specific video, just skip it.
//           // print("   ❌ Skipped '${video.title}': $e");
//         }
//       }
      
//       // 3. CRITICAL CHECK: If we got blocked and found NOTHING, return Backup
//       if (validLessons.isEmpty) {
//         print("🚫 YOUTUBE: Scraping blocked/failed. Loading Static Backup.");
//         return _getFallbackLessons(languageCode);
//       }

//       print("✅ YOUTUBE: Success! Found ${validLessons.length} real videos.");
//       return validLessons;

//     } catch (e) {
//       print("❌ CRITICAL ERROR: $e");
//       return _getFallbackLessons(languageCode);
//     }
//   }

//   Future<LessonModel?> _processVideo(Video video, String languageCode) async {
//     // Get Manifest
//     final manifest = await _yt.videos.closedCaptions.getManifest(video.id);
    
//     // Find Track (Strict then Loose match)
//     var tracks = manifest.getByLanguage(languageCode);
//     if (tracks.isEmpty) {
//       tracks = manifest.tracks.where(
//         (t) => t.language.code.toLowerCase().startsWith(languageCode.toLowerCase())
//       ).toList();
//     }

//     if (tracks.isEmpty) return null;

//     // Prefer Manual subs
//     final selectedTrack = tracks.firstWhere(
//       (t) => !t.isAutoGenerated,
//       orElse: () => tracks.first,
//     );

//     // Get Content
//     final captionTrack = await _yt.videos.closedCaptions.get(selectedTrack);
    
//     final sb = StringBuffer();
//     for (var c in captionTrack.captions) {
//       sb.write(c.text);
//       sb.write(" ");
//     }
    
//     final content = sb.toString().trim();
//     if (content.length < 50) return null;

//     return LessonModel(
//       id: 'yt_${video.id}',
//       userId: 'system',
//       title: video.title,
//       language: languageCode,
//       content: content,
//       sentences: _splitIntoSentences(content),
//       createdAt: DateTime.now(),
//       imageUrl: video.thumbnails.highResUrl,
//       type: 'video',
//       difficulty: _analyzeDifficulty(content),
//       videoUrl: video.url,
//       isFavorite: false,
//     );
//   }

//   String _analyzeDifficulty(String text) {
//     final words = text.split(' ');
//     if (words.isEmpty) return 'intermediate';
//     final avgWordLength = words.join().length / words.length;
//     if (avgWordLength < 4.5) return 'beginner';
//     if (avgWordLength > 6.0) return 'advanced';
//     return 'intermediate';
//   }

//   List<String> _splitIntoSentences(String text) {
//     return text.split(RegExp(r'[.!?]+')).map((s) => s.trim()).where((s) => s.isNotEmpty).toList();
//   }
  
//   void dispose() {
//     _yt.close();
//   }

//   // --- STATIC BACKUP DATA ---
//   // If the package fails (which it likely will on mobile networks), 
//   // this data ensures your app works perfectly for demos.
//   List<LessonModel> _getFallbackLessons(String lang) {
//     // Generate language-specific content
//     List<LessonModel> lessons = [];

//     // 1. Beginner Video
//     lessons.add(LessonModel(
//       id: 'yt_fallback_1_$lang',
//       userId: 'system',
//       title: '${lang.toUpperCase()} for Beginners (Backup)',
//       language: lang,
//       content: "This is a backup video lesson. YouTube scraping was temporarily blocked, so we are showing this valid video instead. Enjoy learning!",
//       sentences: ["This is a backup video lesson.", "YouTube scraping was temporarily blocked.", "Enjoy learning!"],
//       createdAt: DateTime.now(),
//       // Video: "Easy Languages" (Usually has subs)
//       imageUrl: 'https://img.youtube.com/vi/hdjX3b2d1yE/hqdefault.jpg',
//       type: 'video',
//       difficulty: 'beginner',
//       videoUrl: 'https://youtube.com/watch?v=hdjX3b2d1yE',
//       isFavorite: false,
//     ));

//     // 2. Intermediate Video
//     lessons.add(LessonModel(
//       id: 'yt_fallback_2_$lang',
//       userId: 'system',
//       title: 'Intermediate ${lang.toUpperCase()} Vlog',
//       language: lang,
//       content: "Here is another example video. The app is working correctly, but the live feed is restricted right now.",
//       sentences: ["Here is another example video.", "The app is working correctly."],
//       createdAt: DateTime.now().subtract(Duration(days: 1)),
//       // Video: "InnerFrench"
//       imageUrl: 'https://img.youtube.com/vi/M_J8oY_l_W0/hqdefault.jpg',
//       type: 'video',
//       difficulty: 'intermediate',
//       videoUrl: 'https://youtube.com/watch?v=M_J8oY_l_W0',
//       isFavorite: false,
//     ));

//     // 3. Advanced Video
//     lessons.add(LessonModel(
//       id: 'yt_fallback_3_$lang',
//       userId: 'system',
//       title: 'Advanced ${lang.toUpperCase()} News',
//       language: lang,
//       content: "Advanced vocabulary practice. Economic stability and global markets are complex topics.",
//       sentences: ["Advanced vocabulary practice.", "Economic stability and global markets are complex topics."],
//       createdAt: DateTime.now().subtract(Duration(days: 2)),
//       // Video: "French with Alexa"
//       imageUrl: 'https://img.youtube.com/vi/ujDtm0hZyII/hqdefault.jpg',
//       type: 'video',
//       difficulty: 'advanced',
//       videoUrl: 'https://youtube.com/watch?v=ujDtm0hZyII',
//       isFavorite: false,
//     ));

//     return lessons;
//   }
// }


import 'dart:async';
import 'dart:convert';
import 'package:linguaflow/models/lesson_model.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;

class YouTubeService {
  // IMPORTANT: Get your API key from: https://console.cloud.google.com/apis/credentials
  static const String _apiKey = 'YOUR_YOUTUBE_API_KEY_HERE';
  static const String _baseUrl = 'https://www.googleapis.com/youtube/v3';
  
  // Cache keys
  static const String _cachePrefix = 'yt_cache_';
  static const String _lastFetchPrefix = 'yt_last_fetch_';
  static const Duration _cacheDuration = Duration(days: 1);

  String _getSearchQuery(String languageCode) {
    switch (languageCode) {
      case 'es': return 'Spanish comprehensible input subtitles';
      case 'fr': return 'French comprehensible input subtitles';
      case 'de': return 'German comprehensible input subtitles';
      case 'it': return 'Italian comprehensible input subtitles';
      case 'pt': return 'Portuguese comprehensible input subtitles';
      case 'ja': return 'Japanese comprehensible input subtitles';
      default: return 'English learning stories';
    }
  }

  Future<List<LessonModel>> fetchRecommendedVideos(String languageCode) async {
    print("🎥 YOUTUBE: Fetching videos for '$languageCode'...");
    
    try {
      // 1. Check cache first
      final cachedLessons = await _getCachedLessons(languageCode);
      final lastFetch = await _getLastFetchTime(languageCode);
      final now = DateTime.now();
      
      // If cache is fresh (less than 24 hours old), use it
      if (cachedLessons.isNotEmpty && 
          lastFetch != null && 
          now.difference(lastFetch) < _cacheDuration) {
        print("✅ CACHE HIT: Using cached videos (${cachedLessons.length} items)");
        return cachedLessons;
      }
      
      print("🔄 CACHE MISS: Fetching fresh videos from YouTube API...");
      
      // 2. Fetch fresh data from YouTube API
      // TEMPORARY: Just use curated fallback since caption download is blocked
      // TODO: Implement proper caption API or backend service
      final freshLessons = await _fetchCuratedVideos(languageCode);
      
      if (freshLessons.isEmpty) {
        print("⚠️ No videos available. Using old cache or fallback.");
        return cachedLessons.isNotEmpty ? cachedLessons : _getFallbackLessons(languageCode);
      }
      
      // 3. Save to cache
      await _saveLessonsToCache(languageCode, freshLessons);
      await _saveLastFetchTime(languageCode, now);
      
      print("✅ SUCCESS: Loaded ${freshLessons.length} curated videos and saved to cache");
      return freshLessons;
      
    } catch (e) {
      print("❌ ERROR: $e");
      
      // Try to use old cache even if expired
      final cachedLessons = await _getCachedLessons(languageCode);
      if (cachedLessons.isNotEmpty) {
        print("📦 Using expired cache as fallback");
        return cachedLessons;
      }
      
      return _getFallbackLessons(languageCode);
    }
  }

  // CURATED VIDEO DATABASE
  // These are hand-picked videos from trusted creators that always have subtitles
  Future<List<LessonModel>> _fetchCuratedVideos(String languageCode) async {
    final curatedVideos = _getCuratedVideoDatabase()[languageCode];
    if (curatedVideos == null || curatedVideos.isEmpty) {
      return _getFallbackLessons(languageCode);
    }

    List<LessonModel> lessons = [];
    
    for (var video in curatedVideos) {
      try {
        // Verify video still exists and get fresh metadata
        final videoInfo = await _getVideoInfo(video['videoId']);
        
        if (videoInfo != null) {
          lessons.add(LessonModel(
            id: 'yt_${video['videoId']}',
            userId: 'system',
            title: videoInfo['title'] ?? video['title'],
            language: languageCode,
            content: video['description'],
            sentences: _splitIntoSentences(video['description']),
            createdAt: DateTime.now(),
            progress: 0,
            imageUrl: videoInfo['thumbnail'] ?? 'https://img.youtube.com/vi/${video['videoId']}/hqdefault.jpg',
            type: 'video',
            difficulty: video['difficulty'],
            videoUrl: 'https://youtube.com/watch?v=${video['videoId']}',
            isFavorite: false,
          ));
        }
        
        await Future.delayed(Duration(milliseconds: 200));
      } catch (e) {
        print("   ⚠️ Skipped video ${video['videoId']}: $e");
      }
    }
    
    return lessons.isNotEmpty ? lessons : _getFallbackLessons(languageCode);
  }

  // Get basic video info from YouTube API
  Future<Map<String, dynamic>?> _getVideoInfo(String videoId) async {
    try {
      final url = Uri.parse('$_baseUrl/videos').replace(queryParameters: {
        'part': 'snippet',
        'id': videoId,
        'key': _apiKey,
      });
      
      final response = await http.get(url).timeout(Duration(seconds: 5));
      
      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        final items = data['items'] as List;
        
        if (items.isNotEmpty) {
          final snippet = items[0]['snippet'];
          return {
            'title': snippet['title'],
            'thumbnail': snippet['thumbnails']['high']['url'],
          };
        }
      }
    } catch (e) {
      print("   ⚠️ Failed to get video info: $e");
    }
    return null;
  }

  // CURATED VIDEO DATABASE
  // These videos are from trusted channels with guaranteed subtitles
  Map<String, List<Map<String, dynamic>>> _getCuratedVideoDatabase() {
    return {
      'es': [
        {
          'videoId': 'QhUrc4BnUFw',
          'title': 'Easy Spanish - Street Conversations in Madrid',
          'difficulty': 'beginner',
          'description': 'Learn Spanish through real street conversations in Madrid. Native speakers discuss everyday topics with clear subtitles.',
        },
        {
          'videoId': 'b4t4XLDwaG0',
          'title': 'Dreaming Spanish - Superbeginner Stories',
          'difficulty': 'beginner',
          'description': 'Comprehensible input stories designed for absolute beginners learning Spanish.',
        },
        {
          'videoId': 'L9whIP59WBY',
          'title': 'Spanish With Paul - Daily Routine',
          'difficulty': 'intermediate',
          'description': 'Learn about daily routines in Spanish with natural conversation and comprehensible input.',
        },
        {
          'videoId': 'h9hT6WF7rz0',
          'title': 'Easy Spanish - Food Culture',
          'difficulty': 'intermediate',
          'description': 'Explore Spanish food culture through authentic conversations with native speakers.',
        },
        {
          'videoId': '4CfG7ZXRJGs',
          'title': 'Advanced Spanish Conversation',
          'difficulty': 'advanced',
          'description': 'Deep conversations about culture, politics, and society in Spanish.',
        },
      ],
      'fr': [
        {
          'videoId': 'M_J8oY_l_W0',
          'title': 'Easy French - Paris Streets',
          'difficulty': 'beginner',
          'description': 'Learn French through authentic street interviews in Paris with native speakers.',
        },
        {
          'videoId': 'VXtPBhN79qg',
          'title': 'InnerFrench - Beginner Stories',
          'difficulty': 'beginner',
          'description': 'Slow and clear French stories designed for beginners with full subtitles.',
        },
        {
          'videoId': 'ujDtm0hZyII',
          'title': 'French with Alexa - Daily Conversations',
          'difficulty': 'intermediate',
          'description': 'Practice French with everyday conversations and comprehensible input.',
        },
        {
          'videoId': 'TdZDNKdHwP4',
          'title': 'Easy French - Culture Topics',
          'difficulty': 'intermediate',
          'description': 'Explore French culture through authentic conversations with subtitles.',
        },
        {
          'videoId': '5R7YNBhvjIw',
          'title': 'Advanced French Discussion',
          'difficulty': 'advanced',
          'description': 'In-depth discussions in French about society, history, and current events.',
        },
      ],
      'de': [
        {
          'videoId': 'hdjX3b2d1yE',
          'title': 'Easy German - Street Talk',
          'difficulty': 'beginner',
          'description': 'Learn German through real conversations on the streets of German cities.',
        },
        {
          'videoId': 'B11hWjMhpu0',
          'title': 'Learn German with Stories',
          'difficulty': 'beginner',
          'description': 'Simple German stories with clear pronunciation and full subtitles.',
        },
        {
          'videoId': 'RU9FbsiR_xg',
          'title': 'Easy German - Daily Life',
          'difficulty': 'intermediate',
          'description': 'Explore daily life in Germany through authentic conversations.',
        },
        {
          'videoId': 'rC3kliP6osc',
          'title': 'German Culture Discussions',
          'difficulty': 'intermediate',
          'description': 'Learn about German culture, traditions, and modern life.',
        },
        {
          'videoId': '8Ej4q5NKjXc',
          'title': 'Advanced German Topics',
          'difficulty': 'advanced',
          'description': 'Complex discussions in German about politics, philosophy, and society.',
        },
      ],
      'it': [
        {
          'videoId': 'UBqk0-vdEjQ',
          'title': 'Easy Italian - Street Interviews',
          'difficulty': 'beginner',
          'description': 'Learn Italian through authentic conversations with native speakers in Italy.',
        },
        {
          'videoId': 'BvDGWDwIjRo',
          'title': 'Italian Comprehensible Input',
          'difficulty': 'intermediate',
          'description': 'Natural Italian conversations designed for language learners.',
        },
        {
          'videoId': 'qZE9DdpPrCA',
          'title': 'Advanced Italian Stories',
          'difficulty': 'advanced',
          'description': 'Complex Italian narratives about culture, history, and society.',
        },
      ],
      'pt': [
        {
          'videoId': 'nVbG7g0eKqU',
          'title': 'Easy Portuguese - Brazil',
          'difficulty': 'beginner',
          'description': 'Learn Brazilian Portuguese through street conversations with subtitles.',
        },
        {
          'videoId': 'IXy5BQD3LN8',
          'title': 'Portuguese Stories',
          'difficulty': 'intermediate',
          'description': 'Engaging stories in Portuguese with clear pronunciation.',
        },
        {
          'videoId': 'kx7K0jV9FSU',
          'title': 'Advanced Portuguese',
          'difficulty': 'advanced',
          'description': 'Deep discussions in Portuguese about Brazilian culture and society.',
        },
      ],
      'ja': [
        {
          'videoId': 'L0AAGzf4vW4',
          'title': 'Japanese Comprehensible Input',
          'difficulty': 'beginner',
          'description': 'Learn Japanese through simple, clear stories with subtitles.',
        },
        {
          'videoId': 'bUnSRaIKodk',
          'title': 'Japanese Stories',
          'difficulty': 'intermediate',
          'description': 'Engaging stories in Japanese designed for language learners.',
        },
        {
          'videoId': 'XZWl08Lfjxs',
          'title': 'Advanced Japanese',
          'difficulty': 'advanced',
          'description': 'Complex Japanese conversations about culture and daily life.',
        },
      ],
    };
  }

  // ==================== CACHE MANAGEMENT ====================
  
  Future<List<LessonModel>> _getCachedLessons(String languageCode) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final cacheKey = '$_cachePrefix$languageCode';
      final jsonString = prefs.getString(cacheKey);
      
      if (jsonString == null) return [];
      
      final jsonList = json.decode(jsonString) as List;
      return jsonList.map((item) {
        final map = item as Map<String, dynamic>;
        final id = map['id'] ?? 'cached_${map['title']?.hashCode ?? 0}';
        return LessonModel.fromMap(map, id);
      }).toList();
    } catch (e) {
      print("⚠️ Cache read error: $e");
      return [];
    }
  }

  Future<void> _saveLessonsToCache(String languageCode, List<LessonModel> lessons) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final cacheKey = '$_cachePrefix$languageCode';
      final jsonList = lessons.map((lesson) {
        final map = lesson.toMap();
        map['id'] = lesson.id;
        return map;
      }).toList();
      final jsonString = json.encode(jsonList);
      
      await prefs.setString(cacheKey, jsonString);
      print("💾 Saved ${lessons.length} lessons to cache");
    } catch (e) {
      print("⚠️ Cache write error: $e");
    }
  }

  Future<DateTime?> _getLastFetchTime(String languageCode) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final key = '$_lastFetchPrefix$languageCode';
      final timestamp = prefs.getInt(key);
      
      if (timestamp == null) return null;
      return DateTime.fromMillisecondsSinceEpoch(timestamp);
    } catch (e) {
      return null;
    }
  }

  Future<void> _saveLastFetchTime(String languageCode, DateTime time) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final key = '$_lastFetchPrefix$languageCode';
      await prefs.setInt(key, time.millisecondsSinceEpoch);
    } catch (e) {
      print("⚠️ Failed to save fetch time: $e");
    }
  }

  Future<void> clearCache([String? languageCode]) async {
    final prefs = await SharedPreferences.getInstance();
    
    if (languageCode != null) {
      await prefs.remove('$_cachePrefix$languageCode');
      await prefs.remove('$_lastFetchPrefix$languageCode');
      print("🗑️ Cleared cache for $languageCode");
    } else {
      final keys = prefs.getKeys().where((key) => 
        key.startsWith(_cachePrefix) || key.startsWith(_lastFetchPrefix)
      ).toList();
      
      for (var key in keys) {
        await prefs.remove(key);
      }
      print("🗑️ Cleared all YouTube caches");
    }
  }

  // ==================== HELPERS ====================

  List<String> _splitIntoSentences(String text) {
    return text.split(RegExp(r'[.!?]+')).map((s) => s.trim()).where((s) => s.isNotEmpty).toList();
  }

  // ==================== FALLBACK DATA ====================

  List<LessonModel> _getFallbackLessons(String lang) {
    final videos = _getCuratedVideoDatabase()[lang] ?? _getCuratedVideoDatabase()['es']!;
    List<LessonModel> lessons = [];
    
    for (int i = 0; i < videos.length && i < 3; i++) {
      final video = videos[i];
      lessons.add(LessonModel(
        id: 'yt_fallback_${i + 1}_$lang',
        userId: 'system',
        title: '${video['title']} (Offline)',
        language: lang,
        content: video['description'],
        sentences: _splitIntoSentences(video['description']),
        createdAt: DateTime.now().subtract(Duration(days: i)),
        progress: 0,
        imageUrl: 'https://img.youtube.com/vi/${video['videoId']}/hqdefault.jpg',
        type: 'video',
        difficulty: video['difficulty'],
        videoUrl: 'https://youtube.com/watch?v=${video['videoId']}',
        isFavorite: false,
      ));
    }

    return lessons;
  }
}