// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI3TmiGdTKUeK6HO2_GYB4AS-GWvWzgFw',
    appId: '1:1085234269350:web:732bc3a5dcf2f4afe13867',
    messagingSenderId: '1085234269350',
    projectId: 'linguaflowy',
    authDomain: 'linguaflowy.firebaseapp.com',
    storageBucket: 'linguaflowy.firebasestorage.app',
    measurementId: 'G-V1QNPC4NLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHjU8kTjJRSSrpK1FPm9x3lSMPk4Ji_OY',
    appId: '1:1085234269350:android:0b597fd1819bdbd2e13867',
    messagingSenderId: '1085234269350',
    projectId: 'linguaflowy',
    storageBucket: 'linguaflowy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHRljL7MlmvS_GeH5GwjUjgkCfiPePyEs',
    appId: '1:1085234269350:ios:6530b66eeb22aad3e13867',
    messagingSenderId: '1085234269350',
    projectId: 'linguaflowy',
    storageBucket: 'linguaflowy.firebasestorage.app',
    iosBundleId: 'com.reikom.linguaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHRljL7MlmvS_GeH5GwjUjgkCfiPePyEs',
    appId: '1:1085234269350:ios:6530b66eeb22aad3e13867',
    messagingSenderId: '1085234269350',
    projectId: 'linguaflowy',
    storageBucket: 'linguaflowy.firebasestorage.app',
    iosBundleId: 'com.reikom.linguaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI3TmiGdTKUeK6HO2_GYB4AS-GWvWzgFw',
    appId: '1:1085234269350:web:b3dbc41c20a809b9e13867',
    messagingSenderId: '1085234269350',
    projectId: 'linguaflowy',
    authDomain: 'linguaflowy.firebaseapp.com',
    storageBucket: 'linguaflowy.firebasestorage.app',
    measurementId: 'G-QDP0N1W0EQ',
  );

}