// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcrNZdS9FbrEw9edq9zmWX9aI6yQW72c',
    appId: '1:171340794740:web:7406a9739a0796e8643a21',
    messagingSenderId: '171340794740',
    projectId: 'lingua-flowy',
    authDomain: 'lingua-flowy.firebaseapp.com',
    storageBucket: 'lingua-flowy.firebasestorage.app',
    measurementId: 'G-CDSC5WLEBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wRBs-0x3Nn1ws-iaxKHRiyK2NpPtnMI',
    appId: '1:171340794740:android:ca6bfc1cefd95b31643a21',
    messagingSenderId: '171340794740',
    projectId: 'lingua-flowy',
    storageBucket: 'lingua-flowy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA07e3CmdpQISjPWw4UM_F9AjAFKzNgetk',
    appId: '1:171340794740:ios:ef1e5bad326904f1643a21',
    messagingSenderId: '171340794740',
    projectId: 'lingua-flowy',
    storageBucket: 'lingua-flowy.firebasestorage.app',
    androidClientId: '171340794740-r68eappc1o7s0d89tl2s59ffcfucjpao.apps.googleusercontent.com',
    iosClientId: '171340794740-ar15ji16fnekohhhulunjgjc3net1a3m.apps.googleusercontent.com',
    iosBundleId: 'com.reikom.linguaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA07e3CmdpQISjPWw4UM_F9AjAFKzNgetk',
    appId: '1:171340794740:ios:ef1e5bad326904f1643a21',
    messagingSenderId: '171340794740',
    projectId: 'lingua-flowy',
    storageBucket: 'lingua-flowy.firebasestorage.app',
    androidClientId: '171340794740-r68eappc1o7s0d89tl2s59ffcfucjpao.apps.googleusercontent.com',
    iosClientId: '171340794740-ar15ji16fnekohhhulunjgjc3net1a3m.apps.googleusercontent.com',
    iosBundleId: 'com.reikom.linguaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHcrNZdS9FbrEw9edq9zmWX9aI6yQW72c',
    appId: '1:171340794740:web:31bed35ae3ea0918643a21',
    messagingSenderId: '171340794740',
    projectId: 'lingua-flowy',
    authDomain: 'lingua-flowy.firebaseapp.com',
    storageBucket: 'lingua-flowy.firebasestorage.app',
    measurementId: 'G-V8Y42136Z7',
  );
}
